name: Mon workflow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout du code
              uses: actions/checkout@v4

            - name: Installer les dépendances
              run: npm install
